---

- name: <archlinux> install base packages
  pacman:
    state: present
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-pip
    - npm
    - curl
    - git
    - jq

- name: <archlinux> set vars depend on OS
  set_fact:
    bin_pip3: "/usr/bin/pip3"
    bin_jupyterhub: "/usr/bin/jupyterhub"
