---

- name: <centos> install IUS repo
  yum:
    state: present
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: <centos> install base packages
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - python36u-pip
    - npm
    - curl
    - git
    - jq

- name: <centos> symlink python
  file:
    state: link
    src: "/usr/bin/{{ item }}3.6"
    path: "/usr/local/bin/{{ item }}3"
  with_items:
    - python
    - pip
